Repository qtsoftwarekgl/rdb-unified-services-frontend, pull requests merged in 2024-04, with the labels that each got.

#1 Feature - Implementing feedbacks
  src/components/inputs/Input.tsx
  src/constants/authentication.ts
  src/constants/businessRegistration.ts
  src/helpers/strings.ts
  src/helpers/validations.ts
  src/pages/branch-of-foreign-company/beneficial-owners/BeneficialOwners.tsx
  src/pages/business-registration/NewBusinessRegistration.tsx
  src/pages/business-registration/SelectReservedName.tsx
  src/pages/business-registration/beneficial-owners/BeneficialOwners.tsx
  src/pages/business-registration/capital-information/CapitalDetails.tsx
  src/pages/business-registration/capital-information/CapitalDetailsModal.tsx
  src/pages/business-registration/capital-information/ShareDetails.tsx
  src/pages/business-registration/capital-information/ShareHolders.tsx
  src/pages/business-registration/management/BoardDirectors.tsx
  src/pages/business-registration/management/EmploymentInfo.tsx
  src/pages/business-registration/management/SeniorManagement.tsx
  src/pages/users-management/ForeignUserCard.tsx
  src/pages/users-management/ForeignUsers.tsx
Labels: ready

#4 Feature - Resetting forms
  package.json
  src/components/inputs/DatePicker.tsx
  src/components/inputs/Input.tsx
  src/components/inputs/Select.tsx
  src/components/inputs/TextArea.tsx
  src/pages/branch-of-foreign-company/beneficial-owners/BeneficialOwners.tsx
  src/pages/business-registration/BusinessRegistration.tsx
  src/pages/business-registration/attachments/CompanyAttachments.tsx
  src/pages/business-registration/beneficial-owners/BeneficialOwners.tsx
  src/pages/business-registration/capital-information/CapitalDetails.tsx
  src/pages/business-registration/capital-information/CapitalDetailsModal.tsx
  src/pages/business-registration/capital-information/ShareHolders.tsx
  src/pages/business-registration/general-information/CompanyAddress.tsx
  src/pages/business-registration/general-information/CompanyDetails.tsx
  src/pages/business-registration/management/BoardDirectors.tsx
  src/pages/business-registration/management/EmploymentInfo.tsx
  src/pages/business-registration/management/SeniorManagement.tsx
  src/pages/business-registration/preview-submission/BusinessPreviewSubmission.tsx
Labels: work-in-progress

#6 Fix - Company attachments and preveiw
  src/components/business-registration/PreviewCard.tsx
  src/components/inputs/Button.tsx
  src/constants/authentication.ts
  src/containers/Navbar.tsx
  src/pages/amend-company-details/AmendCompanyDetails.tsx
  src/pages/business-registration/BusinessRegistration.tsx
  src/pages/business-registration/attachments/CompanyAttachments.tsx
  src/pages/business-registration/capital-information/ShareHolders.tsx
  src/pages/business-registration/general-information/BusinessActivity.tsx
  src/pages/business-registration/general-information/CompanyAddress.tsx
  src/pages/business-registration/general-information/CompanyDetails.tsx
  src/pages/business-registration/management/BoardDirectors.tsx
  src/pages/business-registration/management/EmploymentInfo.tsx
  src/pages/business-registration/management/SeniorManagement.tsx
  src/pages/business-registration/preview-submission/BusinessPreviewSubmission.tsx
  src/pages/home/LandingPage.tsx
Labels: work-in-progress, ready

#7 Ft branch of foreign bugs
  src/components/table/Filter.tsx
  src/containers/Navbar.tsx
  src/pages/branch-of-foreign-company/beneficial-owners/BeneficialOwners.tsx
  src/pages/branch-of-foreign-company/general-information/BusinessActivity.tsx
  src/pages/branch-of-foreign-company/management/BoardDirectors.tsx
  src/pages/branch-of-foreign-company/management/SeniorManagement.tsx
  src/pages/branch-of-foreign-company/preview-submission/BusinessPreviewSubmission.tsx
  src/pages/business-registration/beneficial-owners/BeneficialOwners.tsx
  src/pages/business-registration/capital-information/ShareHolders.tsx
  src/pages/enterprise-registration/Preview.tsx
  src/pages/enterprise-registration/enterprise_details/EnterpriseDetails.tsx
  src/pages/transfer-registration/TransferRegistration.tsx
  src/pages/user-applications/UserApplications.tsx
  src/pages/user-company-details/CompanyDetails.tsx
  src/pages/user-company-details/CompanyDocuments.tsx
  src/states/features/userApplicationSlice.ts
Labels: ready
